dtx-company/shared-github-workflows

.github/workflows/build-and-push-and-nonprod-release.yaml, .github/workflows/build-and-push.yaml
This workflow:
* builds and pushes a docker image to JFrog
* pushes a commit to trunk branch of the deployment repo; the commit bumps the image tag to the latest
Used flowcode-generator-server as the first example: https://github.com/dtx-company/flowcode-generator-server/pull/40
Fast follow ups:
* Need a tagging strategy for the shared workflows so that the calling workflows can pin to a version.
* Tuning the custom runners. James said they haven't been tuned at all yet.
* Add fc-services-stg and fc-services-preprod. Can do this after the deployment repo structure is set up.
Open questions/issues:
* We are using the github actions `run_number` as the image tag.  I believe this resets for each workflow, so if we change the workflow name that would start the numbers over from 1 again, which …
=> feat: add workflow to build docker container and trigger deployment to aws nonprod envs

.github/workflows/build-and-push-and-nonprod-release.yaml
The latest run in flowcode-generator-server (https://github.com/dtx-company/flowcode-generator-server/pull/41) actually did use the cache which reduced the docker/build-and-push action from ~20min to 8s.
=> chore: remove TODO because cache is actually working

.github/workflows/build-and-push-and-nonprod-release.yaml
If a change is pushed in the source repository that doesn't result in a new image tag, then the shared workflow should handle that gracefully instead of erroring out with an empty commit. One example of such a change is updating the README.
Separately, I thought it would be nice if the commit that is autogenerated in fc-infra-kubernetes includes a link back to the original commit in the service repository that triggered that autogenerated version bump.
=> feat: gracefully handle case where image doesn't change, and include SHA of the source commit

.github/workflows/conventional-pr-title.yaml
This shared workflow is a thin wrapper around an existing action in marketplace called [semantic-pull-request](https://github.com/marketplace/actions/semantic-pull-request).
Behavior tested on screenshot-service (PR: https://github.com/dtx-company/screenshot-service/pull/39)
* workflow check succeeds if PR title conforms to conventional commits
* workflow check fails if PR title does not conform
* [including the "edited" action](https://github.com/dtx-company/screenshot-service/pull/39/files#diff-456be0857519f7fab1185cb557e9762d5277111df1ef99700f09c2da61ebeb5fR8) will cause the workflow to rerun when the PR title is changed
* edge case of single commit in the PR is handled by enforcing that commit message and PR title match and both follow conventional commit -- …
=> feat: add conventional-pr-title workflow wrapping an existing action from marketplace

.github/workflows/build-and-push-and-nonprod-release.yaml
We are not using fc-services-dev as part of the normal development workflow so this github action does not need to update values.yaml in fc-services-dev.
Story details: https://app.shortcut.com/flowcode/story/46885
=> chore: product engineering team doesn't use fc-services-dev so don't write to it

.github/workflows/build-and-push-and-nonprod-release.yaml
The github actions run_number is not that reliable since it can reset back to 1 if the workflow is updated.
Originally, I wanted to use the github PR number to tag the images built from commits that were squashed merged from PRs, but I couldn't find out how to get that, and there is no guarantee that a commit to trunk came from a PR anyway.
So, the decision is to use the commit SHA. I had already included the SHA as part of the commit message of the autogenerated commit to fc-infra-kubernetes, but this will also tag the images with that SHA.
=> feat: use github sha as the image tag for nonprod workflow

.github/workflows/build-and-push-and-nonprod-release.yaml
* Update logs
* Remove unnecessary permission since we don't use the built in GITHUB_TOKEN for the actions/checkout
* Put quotes around the image tag
Branch name is not descriptive; originally I thought we could get away with using GITHUB_TOKEN instead of passing the PAT down as a secret, but that didn't work and I ended up making a few other small changes instead.
=> feat: small tweaks

.github/workflows/build-and-tag-and-prod-release.yaml
Try using the personal access token instead of the Github token. Perhaps the provided github token doesn't have the right permissions.
Failed [attempt](https://github.com/dtx-company/screenshot-service/runs/6372843632?check_suite_focus=true) on screenshot-service:
```
[3:20:46 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/dtx-company/node-typeorm-boilerplate.git
```
A repo like screenshot-service is built from the the boilerplate [repo](https://github.com/dtx-company/node-typeorm-boilerplate) and so a custom token is likely needed.
I already tried making sure that the dtx team had read permissions to the boilerplate repo, and then I thought the built …
=> fix: add missing fc-infra-kubernetes checkout step to prod release

.github/workflows/build-and-tag-and-prod-release.yaml, README.md
Touch up the messages for the commits that get autogenerated.
It looks like this but should be fixed to say "prod" and also to include the user's full information.
Plus keep documentation up to date!
=> fix: Update commit author and update README with instructions

.github/workflows/build-and-tag-and-prod-release.yaml
The prod workflow is triggered through manual dispatch as opposed to on a push to a branch. The previous thing I did actually didn't work; I needed to read the docs more carefully and test in the throwaway repo some more. Also, email is not available at all through the event.sender object, so I use the no-reply email which is constructed via the id and the username.
=> fix: set user name and email

.github/workflows/build-and-push-and-nonprod-release.yaml
The previous workflows assumed that our values.yaml looked like:
```
fc-service:
process:
tag: foo
...
```
but now they can look like:
```
fc-service:
process:
tag: foo
other-deployment:
process:
tag: foo
another-deployment:
process:
tag: foo
```
so my quick workaround is to let the user pass extra-deployments which will be the names of the other deployments that they wish to have the image tag continuously bumped for. This feels kind of brittle and I would prefer that everything in the deployment.yaml shared a single image tag at a known location, but this will do for now.
Tested here: https://github.com/dtx-company/notifications/pull/328
Also tested that it doesn't break when extra-deployments is not passed: https://github.com/dtx-company/payments/pull/111
=> feat: support updating multiple process.tag in a single values.yaml

.github/workflows/conventional-pr-title.yaml
- Github released a more standard way to handling this edge case -> https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
- These config options aren't needed anymore
=> feat: no need to validate single commit

.github/workflows/build-and-push-and-nonprod-release.yaml
The flowcode API repository needs these two secrets as well in the Build and push step. I ran the flowcode api workflow running against this PR and confirmed it is now building successfully. Additionally, you can see that the build args are being pulled in:
=> chore: allow for PYPI secrets, @barkadosh1

.github/workflows/build-and-push-and-nonprod-release.yaml
Updating the non prod shared workflow to use the org-level secrets that james added.
I ran these changes with changes in Flowcode API (PR to be opened shortly) to test that the new secrets were being pulled in and the build succeeded. See new secrets in the build command below:
=> chore: standardize pypi secret names, @barkadosh1

.github/workflows/build-and-push-and-nonprod-release.yaml
Make the awsenvs configurable so that service owners can use this workflow to release to only stg or only preprod, or whatever environments they want.
Testing in conjunction with https://github.com/dtx-company/flow/pull/6369
When awsenvs is set to only `fc-services-stg`, then it only updates the image tag in stg: https://github.com/dtx-company/fc-infra-kubernetes/commit/c12c7ffb1fb014cd57543f9afe99a9a9e925fb39
=> feat: make awsenvs configurable

.github/workflows/build-and-push-and-nonprod-release.yaml, .github/workflows/build-and-tag-and-prod-release.yaml
To release to usw2 prod, I need to update the workflows to allow the caller to specify multiple regions if they choose. The default for prod is "fc-services-prod/use1", but we could set it to "fc-services-prod/use1,fc-services-prod/usw2" to release to both.
Previously, only the account was configurable and this was already tested. None of the workflow callers are actually setting awsenvs yet, so even though this change is technically a breaking change, it doesn't break any existing callers.
=> feat: support AWS region in addition to AWS account

.github/workflows/conventional-pr-title.yaml
- matches up with angular convention that the release-notes use
- Slack Convo -> https://flowcode.slack.com/archives/C0271ESGNFQ/p1657718464221249?thread_ts=1657718325.067559&cid=C0271ESGNFQ
The default for this action is from commitzen -> https://github.com/commitizen/conventional-commit-types/blob/master/index.json
Which contains some other types that the release-notes doesn't have
=> feat: set possible types for conventional-pr-title

.github/workflows/build-and-push-and-nonprod-release.yaml
Allow the caller to pass in a script to run after the build step and before the release step.
The specific use case is for the flow-app service, which wants to run a specific step after the docker build to push static assets to S3. And flow-app also requires the presence of several build args during the docker build step.
=> feat: support post-build-script and docker-build-args

.github/workflows/build-and-push-and-nonprod-release.yaml, .github/workflows/build-and-tag-and-prod-release.yaml
Make the github actions runner configurable. Still defaults to the generic self-hosted. The reason for this change is primarily to get the frontend builds to run on their own dedicated runners that are bulkier and have node preinstalled among other things. In the future we may have optimized runners to support different service types like our Django or Go services.
=> feat: make the action runner configurable

.github/workflows/build-and-tag-and-prod-release.yaml, .github/workflows/conventional-pr-title.yaml
I'm experimenting with using the conventionalcommit standard instead of the angular standard. The conventionalcommit standard allows a few more types, most notably 'chore', which is heavily used by our engineers and so we want to support it.
=> feat: use conventionalcommit standard and add custom types

config/.npmrc
- This is needed in order for npm to know which registry the global config lives and how to authenticate
=> feat: add .npmrc

.github/workflows/conventional-pr-title.yaml
We agreed in FlowTech that we don't need 'style' as a commit type.
=> chore: remove 'style' as an option

.github/workflows/build-and-tag-and-prod-release.yaml
- used a shared-config publish to jfrog
=> feat: use shared config for semantic release

.github/workflows/tf-module-tag-and-release.yaml
Moved back to calling the shared release, will handle the major release bug via .releaserc files until issue is fixed.
=> tf sem release moved back to shared

.github/workflows/build-and-push-and-deploy-flow-preprod.yaml, .github/workflows/build-and-push-and-deploy-flow-prod.yaml, .github/workflows/build-and-push-and-deploy-flow-stg.yaml, .github/workflows/build-and-push-and-deploy-flow.yaml
We need to remove secrets (like [these](https://github.com/dtx-company/flow/blob/a9ae2dd6f89b285296c11c3280e27b558f915c1c/apps/app/env/.env.production)) from the git repository as its a huge security hole and bad practice.
Because these secrets have been in the git history for so long, we won't clean that from the history but can create and use new secrets after they have been functionally removed from the repo.
Steps:
1. Add environment-level secrets to the GitHub project
2. Update flow and shared-github-workflows repositories to use GH environment secrets
3. Remove secrets from the flow repo.
[Shortcut ticket](https://app.shortcut.com/flowcode/story/89814/remove-secrets-from-flow-git-repo)
=> Fix: use flow environment secrets

.github/workflows/build-and-push-and-deploy-flow.yaml, composite-actions/extract-and-upload-static-assets-flow/action.yaml
Allow flow-app builds to optionally upload the sourcemap files to DataDog.
=> feat: Upload sourcemaps to DataDog

.github/workflows/build-and-push-and-deploy-flow-prod.yaml
This is an update to https://github.com/dtx-company/shared-github-workflows/pull/104 in preparation for the flow deployments using separate workflows per environment. In this case, we want the prod deployment uploading source maps to DataDog so we need to update the parameters.
=> Update flow prod workflow to upload source maps to DataDog

.github/workflows/build-and-push-and-deploy-flow-stg.yaml, composite-actions/update-infra-kubernetes/action.yaml
Use a retry action to retry the git push command if there is an error. We run into errors on the git push that are normally successful on a retry.
```
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details
```
Shortcut tickets:
- [92523](https://app.shortcut.com/flowcode/story/92523/investigate-random-failures-on-infra-push)
- [86887](https://app.shortcut.com/flowcode/story/86887/better-handle-fik-update-step-failures)
=> fix(update-infra-kubernetes): Retry git push
